#!/usr/bin/env python3
"""Vendor and adapt the upstream macroquad JS bundle.

The upstream bundle (macroquad/js/mq_js_bundle.js) is a classic script that
binds to a hard-coded `#glcanvas` element and keeps all of its state (WebGL
context, wasm instance, event handlers) in module scope. That means a single
copy of the bundle can only ever drive one canvas.

This script downloads that bundle and wraps it in a factory so that the
exported `load(wasmPath, canvasId)` creates a fully independent macroquad
instance for the canvas with the given id (or `#id`/`.selector`, or the
element itself). A page can therefore host several canvases while sharing one
`mq_js_bundle.js` file.

Run `just update-js-bundle` to regenerate assets/mq_js_bundle/mq_js_bundle.js.
"""

import hashlib
import pathlib
import sys
import urllib.request

UPSTREAM_URL = "https://raw.githubusercontent.com/not-fl3/macroquad/master/js/mq_js_bundle.js"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "assets" / "mq_js_bundle" / "mq_js_bundle.js"

# Exact snippets from the upstream bundle that have to change. Each one must
# match exactly once, otherwise upstream changed shape and the patches (and the
# wrapper below) need to be reviewed.
PATCHES = [
    # The canvas is now the first argument of load() instead of a hard-coded
    # element.
    (
        'const version=2,canvas=document.querySelector("#glcanvas");',
        "const version=2;",
    ),
    # Do not steal focus when an instance is created: several instances on one
    # page would fight over it.
    (
        "canvas.focus(),",
        "",
    ),
    # window.onresize can only hold one handler, so the last instance loaded
    # would win and earlier canvases would stop resizing. Every instance needs
    # to listen for itself.
    (
        "window.onresize=function(){resize(canvas,wasm_exports.resize)}",
        'window.addEventListener("resize",function(){resize(canvas,wasm_exports.resize)})',
    ),
    # `load` is the name of the exported entry point now, rename the upstream
    # `load(wasmPath)` it wraps.
    (
        "function load(e){var t=fetch(e);",
        "function start(e){var t=fetch(e);",
    ),
]

HEADER = '''/*!
 * MIT License
 *
 * Copyright (c) 2019-2021 Fedor Logachev <not.fl3@gmail.com>
 *
 * This file is generated by tools/build_js_bundle.py; do not edit it by hand.
 * It vendors the upstream macroquad web bundle below and wraps it so that
 * every `load(wasmPath, canvasId)` call creates an independent macroquad
 * instance bound to the given canvas.
 *
 * Upstream: {url}
 * Upstream SHA-256: {sha256}
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
'''

WRAPPER_HEAD = '''
"use strict";

// Resolve a canvas id ("my-canvas"), a selector ("#my-canvas", ".game") or an
// element into the canvas to render into.
function resolve_canvas(canvas_id) {
    if (typeof canvas_id !== "string") {
        return canvas_id;
    }
    const canvas =
        canvas_id[0] === "#" || canvas_id[0] === "."
            ? document.querySelector(canvas_id)
            : document.getElementById(canvas_id);
    if (canvas == null) {
        throw new Error("macroquad: no canvas matches '" + canvas_id + "'");
    }
    return canvas;
}

// Load `wasm_path` into the canvas identified by `canvas_id`. Every call
// creates an independent instance (its own WebGL context, wasm memory and
// event handlers), so one bundle can serve any number of canvases.
export function load(wasm_path, canvas_id = "glcanvas") {
    const canvas = resolve_canvas(canvas_id);

    // The quad_net part of the bundle assigns register_plugin without
    // declaring it, which only works in sloppy mode. This file is a module
    // and modules are always strict, so declare it here.
    let register_plugin;

'''

WRAPPER_TAIL = '''
    return start(wasm_path);
}
'''


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "macroquad-template"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode("utf-8")


def apply_patches(source: str) -> str:
    for old, new in PATCHES:
        count = source.count(old)
        if count != 1:
            sys.exit(
                "error: expected exactly one occurrence of:\n"
                f"  {old!r}\n"
                f"but found {count}. The upstream bundle changed shape; "
                "review tools/build_js_bundle.py."
            )
        source = source.replace(old, new)
    return source


def main() -> None:
    upstream = fetch(UPSTREAM_URL)
    digest = hashlib.sha256(upstream.encode("utf-8")).hexdigest()

    bundle = (
        HEADER.format(url=UPSTREAM_URL, sha256=digest)
        + WRAPPER_HEAD
        + apply_patches(upstream)
        + WRAPPER_TAIL
    )

    OUTPUT.write_text(bundle)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(bundle)} bytes, upstream {digest})")


if __name__ == "__main__":
    main()
