crate_name := `basename "$PWD" | tr '-' '_'`
web_dir := "target/wasm32-unknown-unknown/web-release"
wasm_file := web_dir + "/" + crate_name + ".wasm"

index_file := "<html lang='en'>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>" + crate_name + "</title>
    <style>
        html,
        body,
        canvas {
            margin: 0px;
            padding: 0px;
            width: 100%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            background: black;
            z-index: 0;
        }
    </style>
</head>

<body>
    <canvas id='" + crate_name + "' tabindex='1'></canvas>
    <script type='module'>
        import { load } from './mq_js_bundle.js';

        // One bundle can serve any number of canvases: every load() call gets
        // its own instance bound to the canvas id passed as the second
        // argument.
        load('./" + crate_name + ".wasm', '" + crate_name + "');
    </script>
</body>

</html>"

# Build the current project for the web along with template files
build-web:
    @# build the program
    cargo build --profile=web-release --target wasm32-unknown-unknown

    @# copy the js bundle as is (generated by `just update-js-bundle`) and
    @# write the page that boots the wasm
    @cp assets/mq_js_bundle/mq_js_bundle.js {{web_dir}}/mq_js_bundle.js
    @echo "{{index_file}}" > {{web_dir}}/index.html

    @# shrink the wasm binary
    wasm-snip {{wasm_file}} -o {{wasm_file}}
    wasm-opt -Oz -o {{wasm_file}} {{wasm_file}} --enable-simd --enable-nontrapping-float-to-int --enable-bulk-memory-opt

# Serve the web build locally at http://localhost:8000
serve:
    python3 -m http.server 8000 --directory {{web_dir}}

# Fetch the latest macroquad js bundle and adapt it for this template
update-js-bundle:
    python3 tools/build_js_bundle.py
